function SegmentoT(linha) {
	this.codComp = linha.substring(0, 3);
	this.loteServico = linha.substring(3, 7);
	this.tipoRegistro = linha.substring(7, 8);
	this.numRegistro = linha.substring(8, 13);
	this.codSegmento = linha.substring(13, 14);
	this.codMovimento = linha.substring(15, 17);
	this.numAgencia = linha.substring(17, 22);
	this.digAgencia = linha.substring(22, 23);
	this.numContaCorrente = linha.substring(23, 35);
	this.digContaCorrente = linha.substring(35, 36);
	this.digAgenciaConta = linha.substring(36, 37);
	this.nossoNumero = linha.substring(37, 57);
	this.codCarteira = linha.substring(57, 58);
	this.numDocumento = linha.substring(58, 73);
	this.dataVencimento = linha.substring(73, 81);
	this.vlTitulo = linha.substring(81, 96);
	this.numBancoCobrador = linha.substring(96, 99);
	this.numAgenciaCobradora = linha.substring(99, 104);
	this.digAgenciaCobradora = linha.substring(104, 105);
	this.usoEmpresa = linha.substring(105, 130);
	this.codMoeda = linha.substring(130, 132);
	this.tipoInscricaoSacado = linha.substring(132, 133);
	this.numInscricaoSacado = linha.substring(133, 148);
	this.nomeSacado = linha.substring(148, 188);
	this.numContrato = linha.substring(188, 198);
	this.vlTarifa = linha.substring(198, 213);
	this.motivoOcorrencia = linha.substring(213, 223);
	this.print();
};

SegmentoT.prototype.print = function() {
	console.log("{------- SEGMENTO T -------}"); 
	console.log("|| Código de Compensação: " + this.codComp);
	console.log("|| Lote de Serviço: " + this.loteServico);
	console.log("|| Tipo de Registro: " + this.tipoRegistro);
	console.log("|| Numero do Registro: " + this.numRegistro);
	console.log("|| Codigo do Segmento: " + this.codSegmento);
	console.log("|| Codigo de Movimento: " + this.codMovimento);
	console.log("|| Numero da Agencia: " + this.numAgencia);
	console.log("|| Digito da Agencia: " + this.digAgencia);
	console.log("|| Numero da Conta Corrente: " + this.numContaCorrente);
	console.log("|| Digito da Conta Corrente: " + this.digContaCorrente);
	console.log("|| Digito da Agencia/Conta: " + this.digAgenciaConta);
	console.log("|| Nosso Numero: " + this.nossoNumero);
	console.log("|| Codigo da Carteira: " + this.codCarteira);
	console.log("|| Numero do Documento: " + this.numDocumento);
	console.log("|| Data de Vencimento: " + this.dataVencimento);
	console.log("|| Valor do Titulo: " + this.vlTitulo);
	console.log("|| Numero do Banco Cobrador: " + this.numBancoCobrador);
	console.log("|| Numero da Agencia Cobradora: " + this.numAgenciaCobradora);
	console.log("|| Digito da Agencia Cobradora: " + this.digAgenciaCobradora);
	console.log("|| Uso Empresa: " + this.usoEmpresa);
	console.log("|| Codigo de Moeda: " + this.codMoeda);
	console.log("|| Tipo de Inscricao do Sacado: " + this.tipoInscricaoSacado);
	console.log("|| Numero de Inscricao do Sacado: " + this.numInscricaoSacado);
	console.log("|| Nome do Sacado: " + this.nomeSacado);
	console.log("|| Numero do Contrato: " + this.numContrato);
	console.log("|| Valor da Tarifa: " + this.vlTarifa);
	console.log("|| Motivo de Ocorrencia: " + this.motivoOcorrencia);
	console.log("{------- FIM SEGMENTO T -------}\n")
};

module.exports = SegmentoT;