function SegmentoU(linha) {
	this.codComp = linha.substring(0, 3);
	this.loteServico = linha.substring(3, 7);
	this.tipoRegistro = linha.substring(7, 8);
	this.numRegistro = linha.substring(8, 13);
	this.codSegmento = linha.substring(13, 14);
	this.codMovimento = linha.substring(15, 17);
	this.acrescimos = linha.substring(17, 32);
	this.vlDesconto = linha.substring(32, 47);
	this.vlAbatimento = linha.substring(47, 62);
	this.vlIOF = linha.substring(62, 77);
	this.vlPago = linha.substring(77, 92);
	this.vlLiquido = linha.substring(92, 107);
	this.vlDespesasCedente = linha.substring(107, 122);
	this.vlCreditosCedente = linha.substring(122, 137);
	this.dataOcorrenciaCedente = linha.substring(137, 145);
	this.dataEfetivacaoCreditoCedente = linha.substring(145, 153);
	this.codOcorrenciaSacado = linha.substring(153, 157);
	this.dataOcorrenciaSacado = linha.substring(157, 165);
	this.vlOcorrenciaSacado = linha.substring(165, 180);
	this.complementoOcorrenciaSacado = linha.substring(180, 210);
	this.codBancoCorrespondente = linha.substring(210, 213);
	this.nossoNumeroBancoCorrespondente = linha.substring(213, 233);
	this.print();
};

SegmentoU.prototype.print = function() {
	console.log("{------- SEGMENTO U -------}"); 
	console.log("|| Código de Compensação: " + this.codComp);
	console.log("|| Lote de Serviço: " + this.loteServico);
	console.log("|| Tipo de Registro: " + this.tipoRegistro);
	console.log("|| Numero de Registro: " + this.numRegistro);
	console.log("|| Codigo de Segmento: " + this.codSegmento);
	console.log("|| Codigo de Movimento: " + this.codMovimento);
	console.log("|| Acrescimos: " + this.acrescimos);
	console.log("|| Desconto: " + this.vlDesconto);
	console.log("|| Abatimento: " + this.vlAbatimento);
	console.log("|| Valor IOF: " + this.vlIOF);
	console.log("|| Valor Pago: " + this.vlPago);
	console.log("|| Valor Liquido: " + this.vlLiquido);
	console.log("|| Valor Despesa Cedente: " + this.vlDespesasCedente);
	console.log("|| Valor Creditos Cedente: " + this.vlCreditosCedente);
	console.log("|| Data Ocorrencia Cedente: " + this.dataOcorrenciaCedente);
	console.log("|| Data Efetivacao Credito Cedente: " + this.dataEfetivacaoCreditoCedente);
	console.log("|| Codigo Ocorrencia do Sacado: " + this.codOcorrenciaSacado);
	console.log("|| Data de Ocorrencia do Sacado: " + this.dataOcorrenciaSacado);
	console.log("|| Valor de Ocorrencia do Sacado: " + this.vlOcorrenciaSacado);
	console.log("|| Complemento de Ocorrencia do Sacado: " + this.complementoOcorrenciaSacado);
	console.log("|| Codigo do Banco Correspondente: " + this.codBancoCorrespondente);
	console.log("|| Nosso Numero do Banco Correspondente: " + this.nossoNumeroBancoCorrespondente);
	console.log("{------- FIM SEGMENTO U -------}\n"); 
};

module.exports = SegmentoU;